### ISSUE TITLE
Unable to create keys

### ISSUE THREAD

**Issue by SwimmingFish849** [MrPig91/PSMimecast#2]
I'm trying to use this module but get the below error:

 New-MimecastAPIKeys

cmdlet New-MimecastAPIKeys at command pipeline position 1
Supply values for the following parameters:
AppId: XXXXXXXXXXXXXXXXXXX
Credentials
New-MimecastAPIKeys : Unable to create keys
At line:1 char:1
+ New-MimecastAPIKeys
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-MimecastAPIKeys

**Comment by MrPig91** [comment]
Hey @SwimmingFish849 , sorry you ran into an error trying to use this module. I looked over the function that produced the error and I am unable to see what would cause it. The WriteErrorException happens when a string is given to Write-Error instead of an error record. The only write-error I find in that function is on line 45, although maybe the error occurred in the other functions it called. I use the parameter "Message" for this Write-Error, however as a positional parameter. When I get home I will see if I can make some changes that resolve this issue.

**Comment by SwimmingFish849** [comment]
Thanks, if there is anything I can try my end just let me know :)

**Comment by MrPig91** [comment]
I updated the New-MimecastAPIKey function by calling Message parameter explicitly. I do not think this was the cause of the issue, but is the first obvious thing to try and change. Did you install the module from the Powershell Gallery? I also added the message returned from Mimecast to the error that should tell why an API key was not created, so this should shine light on the error as well. Please note there are 2 authentication methods for Mimecast, Basic-Cloud and Basic-AD. If you have MFA enabled you will need to use Basic-Cloud authtype (now the default).

**Comment by SwimmingFish849** [comment]
Hey - this was installed from the Powershell Gallery, has it been updated on there?

**Comment by SwimmingFish849** [comment]
I think the issue i'm getting is the get-credential command on the new-mimecastapikeys line doesn't prompt for MFA which is why it fails

**Comment by MrPig91** [comment]
Yeah I updated the PSGallery module. I actually ran into a similar issue when we enabled MFA at my company. I had to to use the cloud password instead of my AD credentials. I actually changed the default authentication method to use the "Basic-Cloud" authentication. You specify the auth method using the parameter "-AuthType" , but the default is now Basic-Cloud. I am unaware of a way to get MFA to work with AD authentication unfortunately.

**Comment by SwimmingFish849** [comment]
I ended up turning 2FA off temporarily and still had the same error come up which is odd.
I'll see if Mimecast have any ideas

**Comment by SwimmingFish849** [comment]
Ok, I think we are getting somewhere. 
The URL used https://us-api.mimecast.com/api/login/login is the incorrect region for my account. The correct region is https://eu-api.mimecast.com/api/login/login. 
How can I change that?

**Comment by MrPig91** [comment]
Ohhh! Dang, I am so sorry I wish I would have caught that. I will make an update so that you can chose which region to use as a parameter when setting up the API key.

**Comment by MrPig91** [comment]
I have updated the module. I fixed a couple other bugs as well. You can now chose your region when setting api keys. I just tested it out and appears to be working now. Thank you for bringing this to my attention!

**Comment by SwimmingFish849** [comment]
Excellent, thats all working now - thank you :)
